# Generated by Django 5.1 on 2024-09-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
